name: Build & Release Go Binaries

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    name: Build (${{ matrix.os }})
    runs-on: ${{ matrix.runner }}

    strategy:
      matrix:
        include:
          - os: linux
            runner: ubuntu-latest
            goos: linux
            goarch: amd64
            ext: ""
          - os: linux
            runner: ubuntu-latest
            goos: linux
            goarch: arm64
            ext: ""
          - os: macos
            runner: ubuntu-latest
            goos: darwin
            goarch: amd64
            ext: ""
          - os: macos
            runner: ubuntu-latest
            goos: darwin
            goarch: arm64
            ext: ""
          - os: windows
            runner: ubuntu-latest
            goos: windows
            goarch: amd64
            ext: ".exe"

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Setup Go
        uses: actions/setup-go@v7
        with:
          go-version: "1.26"

      - name: Build
        run: |
          mkdir -p dist
          CGO_ENABLED=0 GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} \
          go build -trimpath -ldflags="-s -w -X main.version=${{ github.ref_name }}" \
          -o dist/simplehttpserver-${{ matrix.goos }}-${{ matrix.goarch }}${{ matrix.ext }}

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: simplehttpserver-${{ matrix.goos }}-${{ matrix.goarch }}
          path: dist/*

  release:
    name: Publish Release
    needs: build
    runs-on: ubuntu-latest
    if: github.ref_type == 'tag'

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v8
        with:
          path: dist

      - name: Display files
        run: ls -R dist

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v3
        with:
          files: dist/**/*
